"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.selfMatchingRouter = void 0;
const express_1 = require("express");
const adminAuth_1 = require("./adminAuth");
const adminApprove_1 = require("./adminApprove");
const adminHistory_1 = require("./adminHistory");
const adminPending_1 = require("./adminPending");
const adminReject_1 = require("./adminReject");
const claimSchedule_1 = require("./claimSchedule");
const listCandidates_1 = require("./listCandidates");
const withdrawClaim_1 = require("./withdrawClaim");
exports.selfMatchingRouter = (0, express_1.Router)();
exports.selfMatchingRouter.get("/candidates", listCandidates_1.handleListSelfMatchingCandidates);
exports.selfMatchingRouter.post("/claim", claimSchedule_1.handleClaimSchedule);
exports.selfMatchingRouter.post("/withdraw", withdrawClaim_1.handleWithdrawClaim);
exports.selfMatchingRouter.get("/admin/pending", adminAuth_1.requireAdmin, adminPending_1.handleAdminPending);
exports.selfMatchingRouter.get("/admin/history", adminAuth_1.requireAdmin, adminHistory_1.handleAdminHistory);
exports.selfMatchingRouter.post("/admin/approve", adminAuth_1.requireAdmin, adminApprove_1.handleAdminApprove);
exports.selfMatchingRouter.post("/admin/reject", adminAuth_1.requireAdmin, adminReject_1.handleAdminReject);
